### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by hcoohb** [sergiomb2/google-drive-ocamlfuse#1]
Hi,

First of all Thank you very much for packaging google-drive-ocaml for fedora!
And this is not really an issue but rather a question.
I noticed that the built package does not show any dependency at all.
It seems to work fine on my system but digging a bit deeper, it seems that the ubuntu repository (by the main developer) shows a few dependency for the package:
Depends: libc6 (>= 2.15), libcurl3-gnutls (>= 7.16.2), libfuse2 (>= 2.8.1), libsqlite3-0 (>= 3.5.9), zlib1g (>= 1:1.1.4)

Should we adapt them to fedora and add them to the package?

Regards,
Fabien

**Comment by sergiomb2** [comment]
rpm do that dependencies automatically:
`rpm -q google-drive-ocamlfuse --requires`
libc.so.6()(64bit)
libc.so.6(GLIBC_2.11)(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.15)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.2)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libc.so.6(GLIBC_2.8)(64bit)
libcurl.so.4()(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libfuse.so.2()(64bit)
libfuse.so.2(FUSE_2.2)(64bit)
libfuse.so.2(FUSE_2.6)(64bit)
libfuse.so.2(FUSE_2.8)(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
librt.so.1()(64bit)
librt.so.1(GLIBC_2.2.5)(64bit)
librt.so.1(GLIBC_2.3.3)(64bit)
libsqlite3.so.0()(64bit)
libz.so.1()(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
rtld(GNU_HASH)

**Comment by hcoohb** [comment]
Oh, I see,
I wasn't aware of that..
My bad then
Thanks for the explanation
