### ISSUE TITLE
Fedora 25 support for Gdrive

### ISSUE THREAD

**Issue by nberdugo** [sergiomb2/google-drive-ocamlfuse#2]
Hello, do you plan to provide a package for Fedora 25?

Thanks for your answer
Nicolas

**Comment by sergiomb2** [comment]
Hi, thanks for reporting , I just finish to  build 	new google-drive-ocamlfuse 	0.6.2 with gapi-ocaml 	0.3.1 and ocamlfuse 2.7.1-2.cvs4 and included F25 builds  [1] 


[1] https://copr.fedorainfracloud.org/coprs/sergiomb/google-drive-ocamlfuse/monitor/detailed

**Comment by nberdugo** [comment]
Thanks very much, i'll try that!                                                                                                                                                                        Envoyé depuis BlackBerry Hub pour Android                                                                                                                                                                            De: notifications@github.comEnvoyé: 6 décembre 2016 19:22À: google-drive-ocamlfuse@noreply.github.comRépondre à: reply@reply.github.comCc: nberdugo@gmail.com; author@noreply.github.comObjet: Re: [sergiomb2/google-drive-ocamlfuse] Fedora 25 support for Gdrive (#2)  Hi, thanks for reporting , I just finish to  build 	new google-drive-ocamlfuse 	0.6.2 with gapi-ocaml 	0.3.1 and ocamlfuse 2.7.1-2.cvs4 and included F25 builds  [1]
[1] https://copr.fedorainfracloud.org/coprs/sergiomb/google-drive-ocamlfuse/monitor/detailed

**Comment by sergiomb2** [comment]
I believe it is fixed ;)
