### ISSUE TITLE
No google-drive-ocamlfuse for fedora 26 x86_64

### ISSUE THREAD

**Issue by HeikoAdams** [sergiomb2/google-drive-ocamlfuse#3]
The latest build has failed for fedora 26 on x86_64

**Comment by sergiomb2** [comment]
Hi, are you heikoada  ? what you plan do when I give you access to copr ? , I will give you access , after the reply ok ?

**Comment by sergiomb2** [comment]
E: Cannot find external tool 'ocamlbuild'

**Comment by HeikoAdams** [comment]
Maybe because the package is named **ocaml-ocamlbuild**

**Comment by sergiomb2** [comment]
building , I also accept Pull requests :)

**Comment by HeikoAdams** [comment]
> Hi, are you heikoada ? what you plan do when I give you access to copr ? , I will give you access , after the reply ok ?

Yes, I am and I want to help you solving those issues ;-)

**Comment by sergiomb2** [comment]
ACL granted , can't fix build of ./google-drive-ocamlfuse-0.6.17-1.fc25.src.rpm , you can see my newest commits

**Comment by HeikoAdams** [comment]
That looks like two ocaml packages are some kind of incompatible. You should file a bugzilla report about this.

**Comment by sergiomb2** [comment]
I count with you to fix this :D

**Comment by sergiomb2** [comment]
fixed https://bugzilla.redhat.com/show_bug.cgi?id=1474762, if you check it let me know . Thanks
