### ISSUE TITLE
Version/Feature Question.

### ISSUE THREAD

**Issue by jbeima** [sergiomb2/google-drive-ocamlfuse#4]
May I ask if there is any rough idea on a timeline when 6.23 or 6.24 might be released in the RedHat/Fedora Corps Repo?

It would be nice to be able to use the new Team Drive capabilities. :)

Please and Thank You!

Again thank you for everything you do!

**Comment by jbeima** [comment]
I should probably also mention I was looking for Fedora 27 x64.

I can appreciate that releasing a new version across all the support platforms can most certainly be a huge undertaking.

**Comment by sergiomb2** [comment]
Please if you do the pull request , I'd appreciate , I have many things to catch up before check your request

**Comment by jbeima** [comment]
I am not sure how a pull request gets an addition done to the Corps Fedora Repo for an RPM of the current version? I am happy to do one, but I don't see how the two go hand in hand?

**Comment by sergiomb2** [comment]
Hi, 
pull requests is for github (here) 

https://github.com/sergiomb2/google-drive-ocamlfuse/tree/master/ocamlfuse
https://github.com/sergiomb2/google-drive-ocamlfuse/tree/master/google-drive-ocamlfuse
https://github.com/sergiomb2/google-drive-ocamlfuse/tree/master/gapi-ocaml

Name:           ocamlfuse  Version: 2.7.1
Name:           gapi-ocaml  Version: 0.3.4
Name:       google-drive-ocamlfuse Version: 0.6.20

What and what version do you think that I should update ? please ?

**Comment by sergiomb2** [comment]
pull request example could be : https://github.com/sergiomb2/google-drive-ocamlfuse/commit/4ae4fdf547cfe5357f70fda4adab0c3d51254f22

we have updates for 
https://github.com/astrada/gapi-ocaml/releases
https://github.com/astrada/google-drive-ocamlfuse/releases

I will try update it soon , thanks for the feedback

**Comment by sergiomb2** [comment]
gapi-ocaml updated to 0.3.6 and google-drive-acamlfuse to 0.6.24 , please test it , and open an issue if find some problem 
Thanks for the report. 

PS : only F27 + , F26 we don't have the new ocaml-installer ...
