### ISSUE TITLE
key issue

### ISSUE THREAD

**Issue by mtk** [sergiomb2/google-drive-ocamlfuse#5]
i'm seeing this:

error: Verifying a signature using certificate F75C19BBB8A0ACDFD29C09906378CDF6A291A840 (sergiomb_google-drive-ocamlfuse (None) <sergiomb#google-drive-ocamlfuse@copr.fedorahosted.org>):
  1. Certificiate 6378CDF6A291A840 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2021-03-08T16:39:58Z
  2. Key 6378CDF6A291A840 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2021-03-08T16:39:58Z

not a show stopper but i'm old now and i like a quiet neighborhood :-).

thoughts?

**Comment by sergiomb2** [comment]
Hi, this is the proper way to report , thank you 
I trying build  google-drive-ocamlfuse for F39 but build fails .

**Comment by mtk** [comment]
not understanding...  /mark

**Comment by sergiomb2** [comment]
@mtk , I corrected my comment ( I'm trying build google-drive-ocamlfuse for F39 but build fails ) , are you trying to install it on Fedora 38 , 39 or rawhide ?

**Comment by sergiomb2** [comment]
Hi, when I wrote, I thought it was a problem on F39+ and new ocaml 5.0.0 .

about the "error: Verifying a signature using certificate dnf fedora copr" 

Try running these commands to get the current key from the server:
  Find the actual COPR key using: rpm -q --qf "%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n" gpg-pubkey | grep google-drive-ocamlfuse
    Remove your current GPG key for the COPR using sudo rpm -e gpg-pubkey-XXXXXXXX-XXXXXXXX (replacing the gpg-pubkey-* with the numbers from step 1.
 
and try dnf install or update again 

reference:
https://forum.kicad.info/t/official-copr-fedora-rpm-repository-gpg-key-expired/42307/2

**Comment by mtk** [comment]
just noticed your reply.  works!  thanks!
