### ISSUE TITLE
Cannot find Fedora Core 34 version

### ISSUE THREAD

**Issue by Patriciogonza9090** [sergiomb2/google-drive-ocamlfuse#6]
Hi Sergio, 

I have installed some years ago the following version from your repository.

google-drive-ocamlfuse-0.7.26-1.fc34.src.rpm

I don´t have a copy of the rpm file, where can I get it?

Thanks for your help.

**Comment by sergiomb2** [comment]
do you want the src.rpm ? it is easy to generated , or you want the binary ?

**Comment by Patriciogonza9090** [comment]
I want the rpm file to install using dnf in my fedora core server 34.

This is the info of the package installed in one server, that I installed many years ago from your repository, now I need to install in a second server same version.

Paquetes instalados
Nombre       : google-drive-ocamlfuse
Versión      : 0.7.26
Lanzamiento  : 1.fc34
Arquitectura : x86_64
Tamaño       : 7.2 M
Fuente       : google-drive-ocamlfuse-0.7.26-1.fc34.src.rpm
Repositorio  : @System
Desde repo   : copr:copr.fedorainfracloud.org:sergiomb:google-drive-ocamlfuse
Resumen      : FUSE filesystem for Google Drive
URL          : http://gdfuse.forge.ocamlcore.org

**Comment by sergiomb2** [comment]
sorry , no , I already dig in my computer

**Comment by sergiomb2** [comment]
I think you just need copy /usr/bin/google-drive-ocamlfuse and install all deps 

rpm -q google-drive-ocamlfuse --requires

libcurl.so.4()(64bit)
libfuse.so.2()(64bit)
libfuse.so.2(FUSE_2.2)(64bit)
libfuse.so.2(FUSE_2.6)(64bit)
libfuse.so.2(FUSE_2.8)(64bit)
libgmp.so.10()(64bit)
libm.so.6()(64bit)
libsqlite3.so.0()(64bit)
libz.so.1()(64bit)

**Comment by Patriciogonza9090** [comment]
Thanks a lot for your help.

Regards!
